name: Deploy the api
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.api
          push: true
          tags: nikhil791/sbl_api:${{ github.sha }}
      - name: Deploy to the VM
        env:
          SHA_TAG: ${{ github.sha }}
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key

          ssh -i ssh_key -o StrictHostKeyChecking=no sbl@34.121.236.140 << EOF
            set -e
            cd /home/sbl/sbl_so

            echo "Updating API_TAG..."
            touch .env
            sed -i "s/^API_TAG=.*/API_TAG=${GITHUB_SHA}/" .env || echo "API_TAG=${GITHUB_SHA}" >> .env

            echo "Stopping old containers..."
            docker compose down --remove-orphans

            echo "Pulling latest images..."
            docker compose pull

            echo "Starting new containers..."
            docker compose up -d --force-recreate

            echo "Cleaning up unused resources..."
            docker system prune -af
          EOF

